include:
  project: weblite-wapps/infrastructure
  ref: master
  file:
    - cicd/wapp-package.gitlab-ci.yml

stages:
  - build
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always
